In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv('diabetes.csv')

In [3]:
df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Pregnancies               768 non-null    int64
 1   Glucose                   768 non-null    int64
 2   BloodPressure             768 non-null    int64
 3   SkinThickness             768 non-null    int64
 4   Insulin                   768 non-null    int64
 5   BMI                       768 non-null    float64
 6   DiabetesPedigreeFunction  768 non-null    float64
 7   Age                       768 non-null    int64
 8   Outcome                   768 non-null    int64
dtypes: float64(2), int64(7)
memory usage: 54.1 KB

In [5]:
df.describe()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
count,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000
mean,3.845052,120.894531,69.105469,20.536458,79.799479,31.992578,0.471876,33.240885,0.348958
std,3.369578,31.972618,19.355807,15.952218,115.244002,7.884160,0.331329,11.760232,0.476951
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.078000,21.000000,0.000000
25%,1.000000,99.000000,62.000000,0.000000,0.000000,27.300000,0.243750,24.000000,0.000000
50%,3.000000,117.000000,72.000000,23.000000,30.500000,32.000000,0.372500,29.000000,0.000000
75%,6.000000,140.250000,80.000000,32.000000,127.250000,36.600000,0.626250,41.000000,1.000000
max,17.000000,199.000000,122.000000,99.000000,846.000000,67.100000,2.420000,81.000000,1.000000

In [6]:
df.corr()['Outcome'].sort_values(ascending=False)

Outcome                     1.000000
Glucose                     0.466581
BMI                         0.292695
Age                         0.238356
Pregnancies                 0.221898
DiabetesPedigreeFunction    0.173844
Insulin                     0.130548
SkinThickness               0.074752
BloodPressure               0.065068
Name: Outcome, dtype: float64

Can See SkinThickness & BloodPressure are not contributing much in Outcome

In [7]:
pip install keras-tuner

Collecting keras-tuner
  Using cached keras_tuner-1.4.8-py3-none-any.whl.metadata (5.6 kB)
Collecting keras (from keras-tuner)
  Using cached keras-3.14.1-py3-none-any.whl.metadata (6.3 kB)
Requirement already satisfied: packaging in c:\users\lenovo\appdata\local\programs\python\python312\lib\site-packages (from keras-tuner) (24.2)
Requirement already satisfied: requests in c:\users\lenovo\appdata\local\programs\python\python312\lib\site-packages (from keras-tuner) (2.32.3)
Collecting kt-legacy (from keras-tuner)
  Using cached kt_legacy-1.0.5-py3-none-any.whl.metadata (221 bytes)
Collecting grpcio (from keras-tuner)
  Using cached grpcio-1.81.1-cp312-cp312-win_amd64.whl.metadata (3.8 kB)
Requirement already satisfied: protobuf in c:\users\lenovo\appdata\local\programs\python\python312\lib\site-packages (from keras-tuner) (4.25.5)
Requirement already satisfied: typing-extensions~=4.12 in c:\users\lenovo\appdata\local\programs\python\python312\lib\site-packages (from grpcio->keras-tuner) (4.15.0)
Requirement already satisfied: absl-py in c:\users\lenovo\appdata\local\programs\python\python312\lib\site-packages (from keras->keras-tuner) (2.1.0)
Requirement already satisfied: numpy in c:\users\lenovo\appdata\local\programs\python\python312\lib\site-packages (from keras->keras-tuner) (2.2.6)
Collecting rich (from keras->keras-tuner)
  Using cached rich-15.0.0-py3-none-any.whl.metadata (18 kB)
Collecting namex (from keras->keras-tuner)
  Using cached namex-0.1.0-py3-none-any.whl.metadata (322 bytes)
Collecting h5py (from keras->keras-tuner)
  Downloading h5py-3.16.0-cp312-cp312-win_amd64.whl.metadata (3.1 kB)
Collecting optree (from keras->keras-tuner)
  Using cached optree-0.19.1-cp312-cp312-win_amd64.whl.metadata (32 kB)
Requirement already satisfied: ml-dtypes in c:\users\lenovo\appdata\local\programs\python\python312\lib\site-packages (from keras->keras-tuner) (0.5.1)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\lenovo\appdata\local\programs\python\python312\lib\site-packages (from requests->keras-tuner) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\lenovo\appdata\local\programs\python\python312\lib\site-packages (from requests->keras-tuner) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\lenovo\appdata\local\programs\python\python312\lib\site-packages (from requests->keras-tuner) (2.2.3)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\lenovo\appdata\local\programs\python\python312\lib\site-packages (from requests->keras-tuner) (2024.8.30)
Collecting markdown-it-py>=2.2.0 (from rich->keras->keras-tuner)
  Using cached markdown_it_py-4.2.0-py3-none-any.whl.metadata (7.4 kB)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\users\lenovo\appdata\roaming\python\python312\site-packages (from rich->keras->keras-tuner) (2.19.1)
Collecting mdurl~=0.1 (from markdown-it-py>=2.2.0->rich->keras->keras-tuner)
  Using cached mdurl-0.1.2-py3-none-any.whl.metadata (1.6 kB)
Using cached keras_tuner-1.4.8-py3-none-any.whl (129 kB)
Using cached grpcio-1.81.1-cp312-cp312-win_amd64.whl (4.9 MB)
Using cached keras-3.14.1-py3-none-any.whl (1.6 MB)
Downloading h5py-3.16.0-cp312-cp312-win_amd64.whl (3.2 MB)
   ---------------------------------------- 0.0/3.2 MB ? eta -:--:--
   ------ --------------------------------- 0.5/3.2 MB 5.6 MB/s eta 0:00:01
   ---------------------------------------- 3.2/3.2 MB 13.3 MB/s  0:00:00
Using cached kt_legacy-1.0.5-py3-none-any.whl (9.6 kB)
Using cached namex-0.1.0-py3-none-any.whl (5.9 kB)
Using cached optree-0.19.1-cp312-cp312-win_amd64.whl (341 kB)
Using cached rich-15.0.0-py3-none-any.whl (310 kB)
Using cached markdown_it_py-4.2.0-py3-none-any.whl (91 kB)
Using cached mdurl-0.1.2-py3-none-any.whl (10.0 kB)
Installing collected packages: namex, kt-legacy, optree, mdurl, h5py, grpcio, markdown-it-py, rich, keras, keras-tuner

   ---- -----------------------------------  1/10 [kt-legacy]
   ---- -----------------------------------  1/10 [kt-legacy]
   -------- -------------------------------  2/10 [optree]
   -------- -------------------------------  2/10 [optree]
   ------------ ---------------------------  3/10 [mdurl]
   ---------------- -----------------------  4/10 [h5py]
   ---------------- -----------------------  4/10 [h5py]
   ---------------- -----------------------  4/10 [h5py]
   ---------------- -----------------------  4/10 [h5py]
   ---------------- -----------------------  4/10 [h5py]
   ---------------- -----------------------  4/10 [h5py]
   ---------------- -----------------------  4/10 [h5py]
   -------------------- -------------------  5/10 [grpcio]
   -------------------- -------------------  5/10 [grpcio]
   -------------------- -------------------  5/10 [grpcio]
   -------------------- -------------------  5/10 [grpcio]
   -------------------- -------------------  5/10 [grpcio]
   ------------------------ ---------------  6/10 [markdown-it-py]
   ------------------------ ---------------  6/10 [markdown-it-py]
   ------------------------ ---------------  6/10 [markdown-it-py]
   ------------------------ ---------------  6/10 [markdown-it-py]
   ------------------------ ---------------  6/10 [markdown-it-py]
   ------------------------ ---------------  6/10 [markdown-it-py]
   ------------------------ ---------------  6/10 [markdown-it-py]
   ---------------------------- -----------  7/10 [rich]
   ---------------------------- -----------  7/10 [rich]
   ---------------------------- -----------  7/10 [rich]
   ---------------------------- -----------  7/10 [rich]
   ---------------------------- -----------  7/10 [rich]
   ---------------------------- -----------  7/10 [rich]
   ---------------------------- -----------  7/10 [rich]
   ---------------------------- -----------  7/10 [rich]
   ---------------------------- -----------  7/10 [rich]
   ---------------------------- -----------  7/10 [rich]
   ---------------------------- -----------  7/10 [rich]
   -------------------------------- -------  8/10 [keras]
   -------------------------------- -------  8/10 [keras]
   -------------------------------- -------  8/10 [keras]
   -------------------------------- -------  8/10 [keras]
   -------------------------------- -------  8/10 [keras]
   -------------------------------- -------  8/10 [keras]
   -------------------------------- -------  8/10 [keras]
   -------------------------------- -------  8/10 [keras]
   -------------------------------- -------  8/10 [keras]
   -------------------------------- -------  8/10 [keras]
   -------------------------------- -------  8/10 [keras]
   -------------------------------- -------  8/10 [keras]
   -------------------------------- -------  8/10 [keras]
   -------------------------------- -------  8/10 [keras]
   -------------------------------- -------  8/10 [keras]
   -------------------------------- -------  8/10 [keras]
   -------------------------------- -------  8/10 [keras]
   -------------------------------- -------  8/10 [keras]
   -------------------------------- -------  8/10 [keras]
   -------------------------------- -------  8/10 [keras]
   -------------------------------- -------  8/10 [keras]
   -------------------------------- -------  8/10 [keras]
   -------------------------------- -------  8/10 [keras]
   -------------------------------- -------  8/10 [keras]
   -------------------------------- -------  8/10 [keras]
   -------------------------------- -------  8/10 [keras]
   -------------------------------- -------  8/10 [keras]
   -------------------------------- -------  8/10 [keras]
   -------------------------------- -------  8/10 [keras]
   -------------------------------- -------  8/10 [keras]
   -------------------------------- -------  8/10 [keras]
   -------------------------------- -------  8/10 [keras]
   -------------------------------- -------  8/10 [keras]
   -------------------------------- -------  8/10 [keras]
   -------------------------------- -------  8/10 [keras]
   -------------------------------- -------  8/10 [keras]
   -------------------------------- -------  8/10 [keras]
   -------------------------------- -------  8/10 [keras]
   -------------------------------- -------  8/10 [keras]
   -------------------------------- -------  8/10 [keras]
   -------------------------------- -------  8/10 [keras]
   -------------------------------- -------  8/10 [keras]
   -------------------------------- -------  8/10 [keras]
   -------------------------------- -------  8/10 [keras]
   -------------------------------- -------  8/10 [keras]
   -------------------------------- -------  8/10 [keras]
   -------------------------------- -------  8/10 [keras]
   -------------------------------- -------  8/10 [keras]
   -------------------------------- -------  8/10 [keras]
   -------------------------------- -------  8/10 [keras]
   -------------------------------- -------  8/10 [keras]
   -------------------------------- -------  8/10 [keras]
   -------------------------------- -------  8/10 [keras]
   -------------------------------- -------  8/10 [keras]
   -------------------------------- -------  8/10 [keras]
   -------------------------------- -------  8/10 [keras]
   -------------------------------- -------  8/10 [keras]
   -------------------------------- -------  8/10 [keras]
   -------------------------------- -------  8/10 [keras]
   -------------------------------- -------  8/10 [keras]
   -------------------------------- -------  8/10 [keras]
   ------------------------------------ ---  9/10 [keras-tuner]
   ------------------------------------ ---  9/10 [keras-tuner]
   ------------------------------------ ---  9/10 [keras-tuner]
   ------------------------------------ ---  9/10 [keras-tuner]
   ------------------------------------ ---  9/10 [keras-tuner]
   ------------------------------------ ---  9/10 [keras-tuner]
   ------------------------------------ ---  9/10 [keras-tuner]
   ---------------------------------------- 10/10 [keras-tuner]

Successfully installed grpcio-1.81.1 h5py-3.16.0 keras-3.14.1 keras-tuner-1.4.8 kt-legacy-1.0.5 markdown-it-py-4.2.0 mdurl-0.1.2 namex-0.1.0 optree-0.19.1 rich-15.0.0
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.2 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [8]:
pip install tensorflow

Collecting tensorflow
  Using cached tensorflow-2.21.0-cp312-cp312-win_amd64.whl.metadata (4.5 kB)
Requirement already satisfied: absl-py>=1.0.0 in c:\users\lenovo\appdata\local\programs\python\python312\lib\site-packages (from tensorflow) (2.1.0)
Collecting astunparse>=1.6.0 (from tensorflow)
  Using cached astunparse-1.6.3-py2.py3-none-any.whl.metadata (4.4 kB)
Collecting flatbuffers>=25.9.23 (from tensorflow)
  Using cached flatbuffers-25.12.19-py2.py3-none-any.whl.metadata (1.0 kB)
Collecting gast!=0.5.0,!=0.5.1,!=0.5.2,>=0.2.1 (from tensorflow)
  Using cached gast-0.7.0-py3-none-any.whl.metadata (1.5 kB)
Collecting google_pasta>=0.1.1 (from tensorflow)
  Using cached google_pasta-0.2.0-py3-none-any.whl.metadata (814 bytes)
Collecting libclang>=13.0.0 (from tensorflow)
  Using cached libclang-18.1.1-py2.py3-none-win_amd64.whl.metadata (5.3 kB)
Requirement already satisfied: opt_einsum>=2.3.2 in c:\users\lenovo\appdata\local\programs\python\python312\lib\site-packages (from tensorflow) (3.4.0)
Requirement already satisfied: packaging in c:\users\lenovo\appdata\local\programs\python\python312\lib\site-packages (from tensorflow) (24.2)
Collecting protobuf<8.0.0,>=6.31.1 (from tensorflow)
  Using cached protobuf-7.35.1-cp310-abi3-win_amd64.whl.metadata (595 bytes)
Requirement already satisfied: requests<3,>=2.21.0 in c:\users\lenovo\appdata\local\programs\python\python312\lib\site-packages (from tensorflow) (2.32.3)
Requirement already satisfied: setuptools in c:\users\lenovo\appdata\local\programs\python\python312\lib\site-packages (from tensorflow) (80.9.0)
Requirement already satisfied: six>=1.12.0 in c:\users\lenovo\appdata\local\programs\python\python312\lib\site-packages (from tensorflow) (1.17.0)
Collecting termcolor>=1.1.0 (from tensorflow)
  Using cached termcolor-3.3.0-py3-none-any.whl.metadata (6.5 kB)
Requirement already satisfied: typing_extensions>=3.6.6 in c:\users\lenovo\appdata\local\programs\python\python312\lib\site-packages (from tensorflow) (4.15.0)
Collecting wrapt>=1.11.0 (from tensorflow)
  Downloading wrapt-2.2.1-cp312-cp312-win_amd64.whl.metadata (7.6 kB)
Requirement already satisfied: grpcio<2.0,>=1.24.3 in c:\users\lenovo\appdata\local\programs\python\python312\lib\site-packages (from tensorflow) (1.81.1)
Requirement already satisfied: keras>=3.12.0 in c:\users\lenovo\appdata\local\programs\python\python312\lib\site-packages (from tensorflow) (3.14.1)
Requirement already satisfied: numpy>=1.26.0 in c:\users\lenovo\appdata\local\programs\python\python312\lib\site-packages (from tensorflow) (2.2.6)
Collecting h5py<3.15.0,>=3.11.0 (from tensorflow)
  Downloading h5py-3.14.0-cp312-cp312-win_amd64.whl.metadata (2.7 kB)
Requirement already satisfied: ml_dtypes<1.0.0,>=0.5.1 in c:\users\lenovo\appdata\local\programs\python\python312\lib\site-packages (from tensorflow) (0.5.1)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\lenovo\appdata\local\programs\python\python312\lib\site-packages (from requests<3,>=2.21.0->tensorflow) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\lenovo\appdata\local\programs\python\python312\lib\site-packages (from requests<3,>=2.21.0->tensorflow) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\lenovo\appdata\local\programs\python\python312\lib\site-packages (from requests<3,>=2.21.0->tensorflow) (2.2.3)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\lenovo\appdata\local\programs\python\python312\lib\site-packages (from requests<3,>=2.21.0->tensorflow) (2024.8.30)
Collecting wheel<1.0,>=0.23.0 (from astunparse>=1.6.0->tensorflow)
  Downloading wheel-0.47.0-py3-none-any.whl.metadata (2.3 kB)
Requirement already satisfied: rich in c:\users\lenovo\appdata\local\programs\python\python312\lib\site-packages (from keras>=3.12.0->tensorflow) (15.0.0)
Requirement already satisfied: namex in c:\users\lenovo\appdata\local\programs\python\python312\lib\site-packages (from keras>=3.12.0->tensorflow) (0.1.0)
Requirement already satisfied: optree in c:\users\lenovo\appdata\local\programs\python\python312\lib\site-packages (from keras>=3.12.0->tensorflow) (0.19.1)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\users\lenovo\appdata\local\programs\python\python312\lib\site-packages (from rich->keras>=3.12.0->tensorflow) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\users\lenovo\appdata\roaming\python\python312\site-packages (from rich->keras>=3.12.0->tensorflow) (2.19.1)
Requirement already satisfied: mdurl~=0.1 in c:\users\lenovo\appdata\local\programs\python\python312\lib\site-packages (from markdown-it-py>=2.2.0->rich->keras>=3.12.0->tensorflow) (0.1.2)
Using cached tensorflow-2.21.0-cp312-cp312-win_amd64.whl (350.9 MB)
Downloading h5py-3.14.0-cp312-cp312-win_amd64.whl (2.9 MB)
   ---------------------------------------- 0.0/2.9 MB ? eta -:--:--
   ---------------------------------------- 2.9/2.9 MB 33.3 MB/s  0:00:00
Using cached protobuf-7.35.1-cp310-abi3-win_amd64.whl (439 kB)
Using cached astunparse-1.6.3-py2.py3-none-any.whl (12 kB)
Downloading wheel-0.47.0-py3-none-any.whl (32 kB)
Using cached flatbuffers-25.12.19-py2.py3-none-any.whl (26 kB)
Using cached gast-0.7.0-py3-none-any.whl (22 kB)
Using cached google_pasta-0.2.0-py3-none-any.whl (57 kB)
Using cached libclang-18.1.1-py2.py3-none-win_amd64.whl (26.4 MB)
Using cached termcolor-3.3.0-py3-none-any.whl (7.7 kB)
Downloading wrapt-2.2.1-cp312-cp312-win_amd64.whl (80 kB)
Installing collected packages: libclang, flatbuffers, wrapt, wheel, termcolor, protobuf, h5py, google_pasta, gast, astunparse, tensorflow

   ----------------------------------------  0/11 [libclang]
   ----------------------------------------  0/11 [libclang]
   ----------------------------------------  0/11 [libclang]
   ----------------------------------------  0/11 [libclang]
  Attempting uninstall: flatbuffers
   ----------------------------------------  0/11 [libclang]
    Found existing installation: flatbuffers 24.12.23
   ----------------------------------------  0/11 [libclang]
    Uninstalling flatbuffers-24.12.23:
   ----------------------------------------  0/11 [libclang]
      Successfully uninstalled flatbuffers-24.12.23
   ----------------------------------------  0/11 [libclang]
   --- ------------------------------------  1/11 [flatbuffers]
   ------- --------------------------------  2/11 [wrapt]
   ------- --------------------------------  2/11 [wrapt]
   ---------- -----------------------------  3/11 [wheel]
   ---------- -----------------------------  3/11 [wheel]
   ---------- -----------------------------  3/11 [wheel]
  Attempting uninstall: protobuf
   ---------- -----------------------------  3/11 [wheel]
    Found existing installation: protobuf 4.25.5
   ---------- -----------------------------  3/11 [wheel]
   ------------------ ---------------------  5/11 [protobuf]
    Uninstalling protobuf-4.25.5:
   ------------------ ---------------------  5/11 [protobuf]
      Successfully uninstalled protobuf-4.25.5
   ------------------ ---------------------  5/11 [protobuf]
   ------------------ ---------------------  5/11 [protobuf]
   ------------------ ---------------------  5/11 [protobuf]
   ------------------ ---------------------  5/11 [protobuf]
   ------------------ ---------------------  5/11 [protobuf]
   ------------------ ---------------------  5/11 [protobuf]
   ------------------ ---------------------  5/11 [protobuf]
   ------------------ ---------------------  5/11 [protobuf]
   ------------------ ---------------------  5/11 [protobuf]
  Attempting uninstall: h5py
   ------------------ ---------------------  5/11 [protobuf]
    Found existing installation: h5py 3.16.0
   ------------------ ---------------------  5/11 [protobuf]
    Uninstalling h5py-3.16.0:
   ------------------ ---------------------  5/11 [protobuf]
      Successfully uninstalled h5py-3.16.0
   ------------------ ---------------------  5/11 [protobuf]
   --------------------- ------------------  6/11 [h5py]
   --------------------- ------------------  6/11 [h5py]
   --------------------- ------------------  6/11 [h5py]
   --------------------- ------------------  6/11 [h5py]
   --------------------- ------------------  6/11 [h5py]
   --------------------- ------------------  6/11 [h5py]
   --------------------- ------------------  6/11 [h5py]
   --------------------- ------------------  6/11 [h5py]
   ------------------------- --------------  7/11 [google_pasta]
   ------------------------- --------------  7/11 [google_pasta]
   ------------------------- --------------  7/11 [google_pasta]
   ----------------------------- ----------  8/11 [gast]
   ------------------------------------ --- 10/11 [tensorflow]
   ------------------------------------ --- 10/11 [tensorflow]
   ------------------------------------ --- 10/11 [tensorflow]
   ------------------------------------ --- 10/11 [tensorflow]
   ------------------------------------ --- 10/11 [tensorflow]
   ------------------------------------ --- 10/11 [tensorflow]
   ------------------------------------ --- 10/11 [tensorflow]
   ------------------------------------ --- 10/11 [tensorflow]
   ------------------------------------ --- 10/11 [tensorflow]
   ------------------------------------ --- 10/11 [tensorflow]
   ------------------------------------ --- 10/11 [tensorflow]
   ------------------------------------ --- 10/11 [tensorflow]
   ------------------------------------ --- 10/11 [tensorflow]
   ------------------------------------ --- 10/11 [tensorflow]
   ------------------------------------ --- 10/11 [tensorflow]
   ------------------------------------ --- 10/11 [tensorflow]
   ------------------------------------ --- 10/11 [tensorflow]
   ------------------------------------ --- 10/11 [tensorflow]
   ------------------------------------ --- 10/11 [tensorflow]
   ------------------------------------ --- 10/11 [tensorflow]
   ------------------------------------ --- 10/11 [tensorflow]
   ------------------------------------ --- 10/11 [tensorflow]
   ------------------------------------ --- 10/11 [tensorflow]
   ------------------------------------ --- 10/11 [tensorflow]
   ------------------------------------ --- 10/11 [tensorflow]
   ------------------------------------ --- 10/11 [tensorflow]
   ------------------------------------ --- 10/11 [tensorflow]
   ------------------------------------ --- 10/11 [tensorflow]
   ------------------------------------ --- 10/11 [tensorflow]
   ------------------------------------ --- 10/11 [tensorflow]
   ------------------------------------ --- 10/11 [tensorflow]
   ------------------------------------ --- 10/11 [tensorflow]
   ------------------------------------ --- 10/11 [tensorflow]
   ------------------------------------ --- 10/11 [tensorflow]
   ------------------------------------ --- 10/11 [tensorflow]
   ------------------------------------ --- 10/11 [tensorflow]
   ------------------------------------ --- 10/11 [tensorflow]
   ------------------------------------ --- 10/11 [tensorflow]
   ------------------------------------ --- 10/11 [tensorflow]
   ------------------------------------ --- 10/11 [tensorflow]
   ------------------------------------ --- 10/11 [tensorflow]
   ------------------------------------ --- 10/11 [tensorflow]
   ------------------------------------ --- 10/11 [tensorflow]
   ------------------------------------ --- 10/11 [tensorflow]
   ------------------------------------ --- 10/11 [tensorflow]
   ------------------------------------ --- 10/11 [tensorflow]
   ------------------------------------ --- 10/11 [tensorflow]
   ------------------------------------ --- 10/11 [tensorflow]
   ------------------------------------ --- 10/11 [tensorflow]
   ------------------------------------ --- 10/11 [tensorflow]
   ------------------------------------ --- 10/11 [tensorflow]
   ------------------------------------ --- 10/11 [tensorflow]
   ------------------------------------ --- 10/11 [tensorflow]
   ------------------------------------ --- 10/11 [tensorflow]
   ------------------------------------ --- 10/11 [tensorflow]
   ------------------------------------ --- 10/11 [tensorflow]
   ------------------------------------ --- 10/11 [tensorflow]
   ------------------------------------ --- 10/11 [tensorflow]
   ------------------------------------ --- 10/11 [tensorflow]
   ------------------------------------ --- 10/11 [tensorflow]
   ------------------------------------ --- 10/11 [tensorflow]
   ------------------------------------ --- 10/11 [tensorflow]
   ------------------------------------ --- 10/11 [tensorflow]
   ------------------------------------ --- 10/11 [tensorflow]
   ------------------------------------ --- 10/11 [tensorflow]
   ------------------------------------ --- 10/11 [tensorflow]
   ------------------------------------ --- 10/11 [tensorflow]
   ------------------------------------ --- 10/11 [tensorflow]
   ------------------------------------ --- 10/11 [tensorflow]
   ------------------------------------ --- 10/11 [tensorflow]
   ------------------------------------ --- 10/11 [tensorflow]
   ------------------------------------ --- 10/11 [tensorflow]
   ------------------------------------ --- 10/11 [tensorflow]
   ------------------------------------ --- 10/11 [tensorflow]
   ------------------------------------ --- 10/11 [tensorflow]
   ------------------------------------ --- 10/11 [tensorflow]
   ------------------------------------ --- 10/11 [tensorflow]
   ------------------------------------ --- 10/11 [tensorflow]
   ------------------------------------ --- 10/11 [tensorflow]
   ------------------------------------ --- 10/11 [tensorflow]
   ------------------------------------ --- 10/11 [tensorflow]
   ------------------------------------ --- 10/11 [tensorflow]
   ------------------------------------ --- 10/11 [tensorflow]
   ------------------------------------ --- 10/11 [tensorflow]
   ------------------------------------ --- 10/11 [tensorflow]
   ------------------------------------ --- 10/11 [tensorflow]
   ------------------------------------ --- 10/11 [tensorflow]
   ------------------------------------ --- 10/11 [tensorflow]
   ------------------------------------ --- 10/11 [tensorflow]
   ------------------------------------ --- 10/11 [tensorflow]
   ------------------------------------ --- 10/11 [tensorflow]
   ------------------------------------ --- 10/11 [tensorflow]
   ------------------------------------ --- 10/11 [tensorflow]
   ------------------------------------ --- 10/11 [tensorflow]
   ------------------------------------ --- 10/11 [tensorflow]
   ------------------------------------ --- 10/11 [tensorflow]
   ------------------------------------ --- 10/11 [tensorflow]
   ------------------------------------ --- 10/11 [tensorflow]
   ------------------------------------ --- 10/11 [tensorflow]
   ------------------------------------ --- 10/11 [tensorflow]
   ------------------------------------ --- 10/11 [tensorflow]
   ------------------------------------ --- 10/11 [tensorflow]
   ------------------------------------ --- 10/11 [tensorflow]
   ------------------------------------ --- 10/11 [tensorflow]
   ------------------------------------ --- 10/11 [tensorflow]
   ------------------------------------ --- 10/11 [tensorflow]
   ------------------------------------ --- 10/11 [tensorflow]
   ------------------------------------ --- 10/11 [tensorflow]
   ------------------------------------ --- 10/11 [tensorflow]
   ------------------------------------ --- 10/11 [tensorflow]
   ------------------------------------ --- 10/11 [tensorflow]
   ------------------------------------ --- 10/11 [tensorflow]
   ------------------------------------ --- 10/11 [tensorflow]
   ------------------------------------ --- 10/11 [tensorflow]
   ------------------------------------ --- 10/11 [tensorflow]
   ------------------------------------ --- 10/11 [tensorflow]
   ------------------------------------ --- 10/11 [tensorflow]
   ------------------------------------ --- 10/11 [tensorflow]
   ------------------------------------ --- 10/11 [tensorflow]
   ------------------------------------ --- 10/11 [tensorflow]
   ------------------------------------ --- 10/11 [tensorflow]
   ------------------------------------ --- 10/11 [tensorflow]
   ------------------------------------ --- 10/11 [tensorflow]
   ------------------------------------ --- 10/11 [tensorflow]
   ------------------------------------ --- 10/11 [tensorflow]
   ------------------------------------ --- 10/11 [tensorflow]
   ------------------------------------ --- 10/11 [tensorflow]
   ------------------------------------ --- 10/11 [tensorflow]
   ------------------------------------ --- 10/11 [tensorflow]
   ------------------------------------ --- 10/11 [tensorflow]
   ------------------------------------ --- 10/11 [tensorflow]
   ------------------------------------ --- 10/11 [tensorflow]
   ------------------------------------ --- 10/11 [tensorflow]
   ------------------------------------ --- 10/11 [tensorflow]
   ------------------------------------ --- 10/11 [tensorflow]
   ------------------------------------ --- 10/11 [tensorflow]
   ------------------------------------ --- 10/11 [tensorflow]
   ------------------------------------ --- 10/11 [tensorflow]
   ------------------------------------ --- 10/11 [tensorflow]
   ------------------------------------ --- 10/11 [tensorflow]
   ------------------------------------ --- 10/11 [tensorflow]
   ------------------------------------ --- 10/11 [tensorflow]
   ------------------------------------ --- 10/11 [tensorflow]
   ------------------------------------ --- 10/11 [tensorflow]
   ------------------------------------ --- 10/11 [tensorflow]
   ------------------------------------ --- 10/11 [tensorflow]
   ------------------------------------ --- 10/11 [tensorflow]
   ------------------------------------ --- 10/11 [tensorflow]
   ------------------------------------ --- 10/11 [tensorflow]
   ------------------------------------ --- 10/11 [tensorflow]
   ------------------------------------ --- 10/11 [tensorflow]
   ------------------------------------ --- 10/11 [tensorflow]
   ------------------------------------ --- 10/11 [tensorflow]
   ------------------------------------ --- 10/11 [tensorflow]
   ------------------------------------ --- 10/11 [tensorflow]
   ------------------------------------ --- 10/11 [tensorflow]
   ------------------------------------ --- 10/11 [tensorflow]
   ------------------------------------ --- 10/11 [tensorflow]
   ------------------------------------ --- 10/11 [tensorflow]
   ------------------------------------ --- 10/11 [tensorflow]
   ------------------------------------ --- 10/11 [tensorflow]
   ------------------------------------ --- 10/11 [tensorflow]
   ------------------------------------ --- 10/11 [tensorflow]
   ------------------------------------ --- 10/11 [tensorflow]
   ------------------------------------ --- 10/11 [tensorflow]
   ------------------------------------ --- 10/11 [tensorflow]
   ------------------------------------ --- 10/11 [tensorflow]
   ------------------------------------ --- 10/11 [tensorflow]
   ------------------------------------ --- 10/11 [tensorflow]
   ------------------------------------ --- 10/11 [tensorflow]
   ------------------------------------ --- 10/11 [tensorflow]
   ------------------------------------ --- 10/11 [tensorflow]
   ------------------------------------ --- 10/11 [tensorflow]
   ------------------------------------ --- 10/11 [tensorflow]
   ------------------------------------ --- 10/11 [tensorflow]
   ------------------------------------ --- 10/11 [tensorflow]
   ------------------------------------ --- 10/11 [tensorflow]
   ------------------------------------ --- 10/11 [tensorflow]
   ------------------------------------ --- 10/11 [tensorflow]

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
mediapipe 0.10.20 requires numpy<2, but you have numpy 2.2.6 which is incompatible.
mediapipe 0.10.20 requires protobuf<5,>=4.25.3, but you have protobuf 7.35.1 which is incompatible.

[notice] A new release of pip is available: 25.2 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [9]:
pip show tensorflow

Name: tensorflow
Version: 2.21.0
Summary: TensorFlow is an open source machine learning framework for everyone.
Home-page: https://www.tensorflow.org/
Author: Google Inc.
Author-email: packages@tensorflow.org
License: Apache 2.0
Location: c:\Users\lenovo\AppData\Local\Programs\Python\Python312\Lib\site-packages
Requires: absl-py, astunparse, flatbuffers, gast, google_pasta, grpcio, h5py, keras, libclang, ml_dtypes, numpy, opt_einsum, packaging, protobuf, requests, setuptools, six, termcolor, typing_extensions, wrapt
Required-by:
Note: you may need to restart the kernel to use updated packages.

In [10]:
import tensorflow

In [11]:
from tensorflow import keras

In [15]:
from keras import Sequential
from keras.layers import Dense

# Now before feeding data to neural network lets scale it